webtalk_init -webtalk_dir C:/Users/guada/OneDrive - UNIVERSIDAD NACIONAL AUTNOMA DE MXICO/Servicio Social/SS_VGA/SS_VGA.sim/sim_1/behav/xsim/xsim.dir/vga_initials_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 26 04:05:48 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3173277" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "96491331-6271-4958-9fdf-1429d3aee0ce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a00321755bb64c458020a71217dc2f31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6588_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1614435477 -regid "" -xml C:/Users/guada/OneDrive - UNIVERSIDAD NACIONAL AUTNOMA DE MXICO/Servicio Social/SS_VGA/SS_VGA.sim/sim_1/behav/xsim/xsim.dir/vga_initials_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/guada/OneDrive - UNIVERSIDAD NACIONAL AUTNOMA DE MXICO/Servicio Social/SS_VGA/SS_VGA.sim/sim_1/behav/xsim/xsim.dir/vga_initials_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/guada/OneDrive - UNIVERSIDAD NACIONAL AUTNOMA DE MXICO/Servicio Social/SS_VGA/SS_VGA.sim/sim_1/behav/xsim/xsim.dir/vga_initials_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
